package com.example.av;

public class Main {
    public static void main(String[] args) {
        Animal kangaroo = Animal.create("kangaroo", 2);
        Animal cat      = Animal.create("cat", 4);
        Animal twin     = Animal.create("cat", 4);

        System.out.println("kangaroo = " + kangaroo);
        System.out.println("cat      = " + cat);
        // equals/hashCode generated by AutoValue.
        System.out.println("cat.equals(twin) = " + cat.equals(twin));
        System.out.println("cat.equals(kangaroo) = " + cat.equals(kangaroo));
    }
}
